services:
  jenkins:
    container_name: dev_jenkins
    build:
      context: .
      dockerfile: ./jenkins.Dockerfile
    restart: always
    ports:
      - 8088:8080
    volumes:
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

  ngrok:
    image: ngrok/ngrok:latest
    container_name: dev_ngrok
    restart: always
    environment:
      NGROK_AUTHTOKEN: CHANGE-ME!!!!!!!!!
    command: "http jenkins:8080"
    ports:
      - 4040:4040
    depends_on:
      - jenkins

volumes:
  jenkins-data:
