services:
  ngrok:
    build:
      context: .
      dockerfile: ./ngrok.Dockerfile
    container_name: dev_ngrok
    restart: always
    environment:
      NGROK_AUTHTOKEN: <CHANGE ME !!!!!!>
    command:
      - "start"
      - "--all"
      - "--config"
      - "/etc/ngrok.yml"
    ports:
      - 4040:4040
    networks:
      - network

networks:
  network:
    driver: bridge
    name: ngrok_network
