services:
  ngroktunnel:
    build:
      context: .
      dockerfile: ./ngrok.Dockerfile
    container_name: ngroktunnel
    restart: always
    environment:
      NGROK_AUTHTOKEN: <CHANGE ME !!!!!!>
    command:
      - "start"
      - "--all"
      - "--config"
      - "/etc/ngrok.yml"
    ports:
      - 4040:4040
    networks:
      - ngroktunnel

networks:
  ngroktunnel:
