services:
  ngrok:
    image: ngrok/ngrok:alpine
    container_name: dev_ngrok
    restart: always
    environment:
      NGROK_AUTHTOKEN: <CHANGE ME !!!!!!>
    command:
      - "start"
      - "--all"
      - "--config"
      - "/etc/ngrok.yml"
    volumes:
      - ./ngrok.yml:/etc/ngrok.yml
    ports:
      - 4040:4040
    networks:
      - network

networks:
  network:
    driver: bridge
    name: ngrok_network
