services:
  ngroktunnel:
    image: ngrok/ngrok:alpine
    container_name: ngroktunnel
    restart: always
    environment:
      NGROK_AUTHTOKEN: <CHANGE ME !!!!!!>
    volumes:
      - ./config/ngrok.yml:/etc/ngrok.yml:ro
    command:
      - "start"
      - "--all"
      - "--config"
      - "/etc/ngrok.yml"
    ports:
      - 4040:4040
    networks:
      - ngroktunnel

networks:
  ngroktunnel:
