services:
  postgres-db:
    image: postgres:alpine
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    container_name: dev_postgresdb
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - dev_dbpgdata:/var/lib/postgresql/data/pgdata

  postgres-pgadmin:
    image: dpage/pgadmin4
    container_name: dev_postgres_pgadmin
    restart: always
    ports:
      - 8888:80
    environment:
      PGADMIN_DEFAULT_EMAIL: pguser@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: pgadmin
    volumes:
      - dev_pgadmindata:/var/lib/pgadmin
    depends_on:
      - postgres-db

volumes:
  dev_dbpgdata:
  dev_pgadmindata:
