services:
  jenkins:
    container_name: jenkins
    build:
      context: .
      dockerfile: ./jenkins.Dockerfile
    restart: always
    ports:
      - 8086:8080
    volumes:
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  jenkins-data:
