services:
  jenkins:
    container_name: dev_jenkins
    build:
      context: .
      dockerfile: ./jenkins.Dockerfile
    restart: always
    ports:
      - 8088:8080
    volumes:
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - jenkins

networks:
  jenkins:
    name: ngrok_network
    external: true

volumes:
  jenkins-data:
