services:
  nginxmanager:
    image: jc21/nginx-proxy-manager:latest
    restart: always
    container_name: nginxmanager
    ports:
      - 80:80
      - 443:443
      - 8085:81
    environment:
      DB_MYSQL_HOST: "db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "npm"
      DB_MYSQL_PASSWORD: "npm"
      DB_MYSQL_NAME: "npm"
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    depends_on:
      - nginxdb

  nginxdb:
    image: jc21/mariadb-aria:latest
    restart: always
    container_name: nginxdb
    environment:
      MYSQL_ROOT_PASSWORD: "npm"
      MYSQL_DATABASE: "npm"
      MYSQL_USER: "npm"
      MYSQL_PASSWORD: "npm"
    volumes:
      - ./mysql:/var/lib/mysql
