services:
  nginxproxymanager:
    image: jc21/nginx-proxy-manager:latest
    restart: always
    container_name: nginxproxymanager
    ports:
      - 80:80
      - 443:443
      - 8085:81
    environment:
      DB_MYSQL_HOST: "db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "npm"
      DB_MYSQL_PASSWORD: "npm"
      DB_MYSQL_NAME: "npm"
    volumes:
      - nginxproxymanager-data:/data
      - nginxproxymanager-ssl:/etc/letsencrypt
    depends_on:
      - nginxdb

  nginxproxymanagerdb:
    image: jc21/mariadb-aria:latest
    restart: always
    container_name: nginxproxymanagerdb
    environment:
      MYSQL_ROOT_PASSWORD: "npm"
      MYSQL_DATABASE: "npm"
      MYSQL_USER: "npm"
      MYSQL_PASSWORD: "npm"
    volumes:
      - nginxproxymanager-db:/var/lib/mysql

volumes:
  nginxproxymanager-data:
  nginxproxymanager-ssl:
  nginxproxymanager-db:
